resources:
  - url: http://127.0.0.1:5000/custom-header.js
    type: module
custom_header:
  footer: true
  background: black
  elements_color: "#fff" # Color of all buttons and tabs
  menu_color: red
  voice_color: rgb(255, 99, 71)
  options_color: var(--text-primary-color)
  all_tabs_color: pink
  tabs_color:
    5: yellow
    home: "#fff"
  chevrons: false # Scroll buttons for tabs
  indicator_top: true # Current tab indicator can be on top or bottom
  hide_tabs: # Can be show_tabs if you prefer
    - 1
    - home # View's title or path may be used
    - 10
views:
  - icon: mdi:house
    cards:
      - type: entities
        entities:
          - sun.sun
  - icon: mdi:account-circle
    cards:
      - type: entities
        entities:
          - sun.sun
