resources:
  - url: http://127.0.0.1:5000/custom-header.js
    type: module
custom_header:
  template_variables: '{% set clock = (now().strftime("%I")|int)~now().strftime(":%M") %}'
  header_text: '{{ clock }}'
  background: '{{ states.input_text.background.state }}'
  menu_color: '{{ states.input_text.menu_color.state }}'
  voice_color: '{{ states.input_text.voice_color.state }}'
  options_color: '{{ states.input_text.options_color.state }}'
  all_tabs_color: '{{ states.input_text.all_tabs_color.state }}'
  indicator_top: '{{ states.input_boolean.indicator_top.state == "on" }}'
  footer: '{{ states.input_boolean.footer.state == "on" }}'
  chevrons: '{{ states.input_boolean.chevrons.state == "on" }}'
  hide_tabs: '{{ states.input_text.hide_tabs.state }}'
  redirect: '{{ states.input_boolean.redirect.state == "on" }}'
  kiosk_mode: '{{ states.input_boolean.kiosk_mode.state == "on" }}'
  compact_mode: '{{ states.input_boolean.compact_mode.state == "on" }}'
  disable_sidebar: '{{ states.input_boolean.disable_sidebar.state == "on" }}'
  tab_direction: '{% if states.input_boolean.tab_direction.state == "on" %}ltr{% else %}rtl{% endif %}'
  button_direction: '{% if states.input_boolean.button_direction.state == "on" %}ltr{% else %}rtl{% endif %}'
  default_tab: '{{ states.input_text.default_tab.state }}'
background: url('https://bit.ly/375dx0T')
views:
  - icon: mdi:pac-man
    title: pacman
    cards:
      - type: entities
        entities:
          - entity: input_boolean.kiosk_mode
          - entity: input_boolean.compact_mode
          - entity: input_boolean.disable_sidebar
          - entity: input_boolean.footer
          - entity: input_boolean.indicator_top
          - entity: input_boolean.chevrons
          - entity: input_boolean.redirect
          - entity: input_boolean.tab_direction
          - entity: input_boolean.button_direction
      - type: entities
        entities:
          - entity: input_text.background
          - entity: input_text.menu_color
          - entity: input_text.voice_color
          - entity: input_text.options_color
          - entity: input_text.all_tabs_color
          - entity: input_text.hide_tabs
          - entity: input_text.default_tab
  - icon: mdi:ghost
    title: ghost
    panel: true
    cards:
      - type: entities
        entities:
          - entity: input_boolean.kiosk_mode
          - entity: input_boolean.compact_mode
          - entity: input_boolean.disable_sidebar
          - entity: input_boolean.footer
          - entity: input_boolean.indicator_top
          - entity: input_boolean.chevrons
          - entity: input_boolean.redirect
          - entity: input_boolean.tab_direction
          - entity: input_boolean.button_direction
          - entity: input_text.background
          - entity: input_text.menu_color
          - entity: input_text.voice_color
          - entity: input_text.options_color
          - entity: input_text.all_tabs_color
          - entity: input_text.hide_tabs
          - entity: input_text.default_tab
  - icon: mdi:skull
    title: skull
  - icon: mdi:bomb
    title: bomb
  - icon: mdi:death-star-variant
    title: death star
  - icon: mdi:space-invaders
    title: invader
  - icon: mdi:triforce
    title: triforce
