resources:
  - url: http://127.0.0.1:5000/custom-header.js
    type: module
custom_header:
  background: '{{ states.input_text.background.state }}'
  menu_color: '{{ states.input_text.menu_color.state }}'
  voice_color: '{{ states.input_text.voice_color.state }}'
  options_color: '{{ states.input_text.options_color.state }}'
  all_tabs_color: '{{ states.input_text.all_tabs_color.state }}'
  indicator_top: '{{ states.input_boolean.indicator_top.state == "on" }}'
  footer: '{{ states.input_boolean.footer.state == "on" }}'
  chevrons: '{{ states.input_boolean.chevrons.state == "on" }}'
  hide_tabs: '{{ states.input_text.hide_tabs.state }}'
background: dimgray
views:
  - icon: mdi:pac-man
    title: pacman
    cards:
      - type: entities
        entities:
          - entity: input_boolean.footer
          - entity: input_boolean.indicator_top
          - entity: input_boolean.chevrons
          - entity: input_text.background
          - entity: input_text.menu_color
          - entity: input_text.voice_color
          - entity: input_text.options_color
          - entity: input_text.all_tabs_color
          - entity: input_text.hide_tabs
  - icon: mdi:ghost
    title: ghost
  - icon: mdi:skull
    title: skull
  - icon: mdi:bomb
    title: bomb
  - icon: mdi:death-star-variant
    title: death star
  - icon: mdi:space-invaders
    title: invader
  - icon: mdi:triforce
    title: triforce
