resources:
  - url: http://127.0.0.1:5000/custom-header.js
    type: module
custom_header:
  template_variables: '{% set clock = (now().strftime("%I")|int)~now().strftime(":%M") %}'
  header_text: '{{ clock }}'
  background: '{{ states.input_text.background.state }}'
  menu_color: '{{ states.input_text.menu_color.state }}'
  voice_color: '{{ states.input_text.voice_color.state }}'
  options_color: '{{ states.input_text.options_color.state }}'
  all_tabs_color: '{{ states.input_text.all_tabs_color.state }}'
  indicator_top: '{{ states.input_boolean.indicator_top.state == "on" }}'
  footer: '{{ states.input_boolean.footer.state == "on" }}'
  chevrons: '{{ states.input_boolean.chevrons.state == "on" }}'
  hide_tabs: '{{ states.input_text.hide_tabs.state }}'
  kiosk_mode: '{{ states.input_boolean.kiosk_mode.state == "on" }}'
  compact_mode: '{{ states.input_boolean.compact_mode.state == "on" }}'
  disable_sidebar: '{{ states.input_boolean.disable_sidebar.state == "on" }}'
background: url('https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/efa5f38e-1b17-45fc-999b-0b5db1804b89/d31qde8-c4f9ca19-6ab4-4e69-b9ad-087d564e6f5f.jpg/v1/fill/w_1024,h_1024,q_75,strp/tileable_wood_texture_01_by_simoonmurray_d31qde8-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTAyNCIsInBhdGgiOiJcL2ZcL2VmYTVmMzhlLTFiMTctNDVmYy05OTliLTBiNWRiMTgwNGI4OVwvZDMxcWRlOC1jNGY5Y2ExOS02YWI0LTRlNjktYjlhZC0wODdkNTY0ZTZmNWYuanBnIiwid2lkdGgiOiI8PTEwMjQifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.sPM3jytY8yve-fgn2pevLnGN7isRo9iqna7nlPrSIgg')
views:
  - icon: mdi:pac-man
    title: pacman
    cards:
      - type: entities
        entities:
          - entity: input_boolean.kiosk_mode
          - entity: input_boolean.compact_mode
          - entity: input_boolean.disable_sidebar
          - entity: input_boolean.footer
          - entity: input_boolean.indicator_top
          - entity: input_boolean.chevrons
      - type: entities
        entities:
          - entity: input_text.background
          - entity: input_text.menu_color
          - entity: input_text.voice_color
          - entity: input_text.options_color
          - entity: input_text.all_tabs_color
          - entity: input_text.hide_tabs
  - icon: mdi:ghost
    title: ghost
    panel: true
    cards:
      - type: entities
        entities:
          - entity: input_boolean.kiosk_mode
          - entity: input_boolean.compact_mode
          - entity: input_boolean.disable_sidebar
          - entity: input_boolean.footer
          - entity: input_boolean.indicator_top
          - entity: input_boolean.chevrons
          - entity: input_text.background
          - entity: input_text.menu_color
          - entity: input_text.voice_color
          - entity: input_text.options_color
          - entity: input_text.all_tabs_color
          - entity: input_text.hide_tabs
  - icon: mdi:skull
    title: skull
  - icon: mdi:bomb
    title: bomb
  - icon: mdi:death-star-variant
    title: death star
  - icon: mdi:space-invaders
    title: invader
  - icon: mdi:triforce
    title: triforce
