  
name: Build
on:
  push:	
    branches:	
      - docs
  pull_request:
    branches:
      - docs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: "bash script/build"
